
# TODO: 
# - should install the default utils: screen, vim, htop, etc ...
# - Should make the user happy to use the vm: bashrc, gitconfig, screenrc, etc ...

- hosts: vagrant
  user: root
  roles:
#  - dumpall
#  - sysadmin
  - sysadmin-centos

